package com.ocean.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LoginName
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LoginPwd
     *
     * @mbg.generated
     */
    private String loginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserType
     *
     * @mbg.generated
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ProfessionID
     *
     * @mbg.generated
     */
    private Integer professionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Arrange
     *
     * @mbg.generated
     */
    private String arrange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DepartmentID
     *
     * @mbg.generated
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.RegisterTypeID
     *
     * @mbg.generated
     */
    private Integer registertypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IsDelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LoginName
     *
     * @return the value of user.LoginName
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LoginName
     *
     * @param loginname the value for user.LoginName
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LoginPwd
     *
     * @return the value of user.LoginPwd
     *
     * @mbg.generated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LoginPwd
     *
     * @param loginpwd the value for user.LoginPwd
     *
     * @mbg.generated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserType
     *
     * @return the value of user.UserType
     *
     * @mbg.generated
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserType
     *
     * @param usertype the value for user.UserType
     *
     * @mbg.generated
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ProfessionID
     *
     * @return the value of user.ProfessionID
     *
     * @mbg.generated
     */
    public Integer getProfessionid() {
        return professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ProfessionID
     *
     * @param professionid the value for user.ProfessionID
     *
     * @mbg.generated
     */
    public void setProfessionid(Integer professionid) {
        this.professionid = professionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Arrange
     *
     * @return the value of user.Arrange
     *
     * @mbg.generated
     */
    public String getArrange() {
        return arrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Arrange
     *
     * @param arrange the value for user.Arrange
     *
     * @mbg.generated
     */
    public void setArrange(String arrange) {
        this.arrange = arrange == null ? null : arrange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DepartmentID
     *
     * @return the value of user.DepartmentID
     *
     * @mbg.generated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DepartmentID
     *
     * @param departmentid the value for user.DepartmentID
     *
     * @mbg.generated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.RegisterTypeID
     *
     * @return the value of user.RegisterTypeID
     *
     * @mbg.generated
     */
    public Integer getRegistertypeid() {
        return registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.RegisterTypeID
     *
     * @param registertypeid the value for user.RegisterTypeID
     *
     * @mbg.generated
     */
    public void setRegistertypeid(Integer registertypeid) {
        this.registertypeid = registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IsDelete
     *
     * @return the value of user.IsDelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IsDelete
     *
     * @param isdelete the value for user.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}